<?php
/**
 * @filesource modules/bp/controllers/sync.php
 *
 * @copyright 2026 Goragod.com
 * @license https://www.kotchasan.com/license/
 *
 * @see https://www.kotchasan.com/
 */

namespace Bp\Sync;

use Gcms\Api as ApiController;
use Kotchasan\Http\Request;

/**
 * api/bp/sync/push|pull - merge records captured while offline
 *
 * push accepts two shapes:
 *   1. a single operation {entity, client_uuid, ...}  <- what SyncManager sends
 *   2. a batch          {operations: [{...}, {...}]} <- for bulk pushes
 *
 * Every operation must carry a client_uuid generated by the device.
 * Together with UNIQUE (member_id, client_uuid) that makes replays harmless.
 *
 * @author Goragod Wiriya <admin@goragod.com>
 *
 * @since 1.0
 */
class Controller extends ApiController
{
    /**
     * Maximum number of operations in one request
     *
     * @var int
     */
    const MAX_OPERATIONS = 100;

    /**
     * @param Request $request
     *
     * @return \Kotchasan\Http\Response
     */
    public function push(Request $request)
    {
        try {
            ApiController::validateMethod($request, 'POST');
            $this->validateCsrfToken($request);
            $this->initLanguage($request);

            $login = $this->authenticateRequest($request);
            if (!$login) {
                return $this->redirectResponse('/login', 'Unauthorized', 401);
            }
            $memberId = (int) $login->id;

            $body = $request->getParsedBody();
            if (!is_array($body)) {
                $body = [];
            }

            $operations = [];
            if (isset($body['operations']) && is_array($body['operations'])) {
                $operations = $body['operations'];
            } elseif (!empty($body)) {
                $operations = [$body];
            }

            if (empty($operations)) {
                return $this->errorResponse('No operations to sync', 400);
            }
            if (count($operations) > self::MAX_OPERATIONS) {
                return $this->errorResponse('Too many operations in one request', 413);
            }

            $applied = [];
            $rejected = [];

            foreach ($operations as $op) {
                if (!is_array($op)) {
                    continue;
                }
                $uuid = isset($op['client_uuid']) ? (string) $op['client_uuid'] : '';
                $entity = isset($op['entity']) ? (string) $op['entity'] : 'record';

                if (!in_array($entity, Model::$entities, true)) {
                    $rejected[] = ['client_uuid' => $uuid, 'reason' => 'unknown entity: '.$entity];
                    continue;
                }

                try {
                    $result = $entity === 'family'
                        ? Model::mergeFamily($op, $memberId)
                        : Model::mergeRecord($op, $memberId);
                } catch (\Exception $e) {
                    $rejected[] = ['client_uuid' => $uuid, 'reason' => $e->getMessage()];
                    continue;
                }

                if ($result['status'] === 'rejected') {
                    // The data failed validation and will fail again on every retry,
                    // so the device must drop it from the queue rather than retry forever
                    $rejected[] = ['client_uuid' => $uuid, 'reason' => $result['reason']];
                } else {
                    $applied[] = [
                        'client_uuid' => $uuid,
                        'entity' => $entity,
                        'id' => $result['id'],
                        'status' => $result['status']
                    ];
                }
            }

            if (!empty($applied)) {
                \Index\Log\Model::add(0, 'bp', 'Sync', 'Synced '.count($applied).' offline record(s)', $memberId);
            }

            return $this->successResponse([
                'applied' => $applied,
                'rejected' => $rejected,
                'server_time' => date('Y-m-d H:i:s')
            ], 'Synced '.count($applied).' item(s)');
        } catch (\Exception $e) {
            return $this->errorResponse($e->getMessage(), $e->getCode() ?: 500, $e);
        }
    }

    /**
     * Pull everything changed since last time, to be cached for offline reading.
     *
     * @param Request $request
     *
     * @return \Kotchasan\Http\Response
     */
    public function pull(Request $request)
    {
        try {
            ApiController::validateMethod($request, 'GET');
            $this->initLanguage($request);

            $login = $this->authenticateRequest($request);
            if (!$login) {
                return $this->errorResponse('Unauthorized', 401);
            }

            $since = $request->get('since')->datetime();
            $limit = min(500, max(1, $request->get('limit', 500)->toInt()));

            return $this->successResponse(
                Model::changesSince($since, (int) $login->id, $limit),
                'OK'
            );
        } catch (\Exception $e) {
            return $this->errorResponse($e->getMessage(), $e->getCode() ?: 500, $e);
        }
    }
}
